server:
  port: 1554
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      deafult-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-service
        uri: lb://usuario-service
        predicates:
          -path=/usuario/**
        - id: moto-service
        uri: lb://moto-service
        predicates:
          -path=/moto/**
        - id: carro-service
        uri: lb://carro-service
        predicates:
          -path=/carro/**
