server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instancias
          uri: https://github.com/santiagoforonda/microservicios-tutorial
          search-paths: config-data
  application:
    name: config-server

